Tensors are multi dimensional arrays
An array is an ordered arrangment of numbers

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [15]:
tensor_one_d = tf.constant([2,0,-3,8,90], dtype=tf.float32)
print(tensor_one_d)
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [16]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [19]:
tensor_string = tf.constant(["Hello World!", "hi"])
print(tensor_string)

tf.Tensor([b'Hello World!' b'hi'], shape=(2,), dtype=string)


In [6]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [7]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [9]:
tensor_three_d.ndim

3

In [11]:
tensor_four_d = tf.constant([
    [
      [[1,2,0],
      [3,5,-1]],

      [[10,2,0],
      [1,0,2]],

      [[5,8,0],
      [2,7,0]],

      [[2,1,9],
      [4,-3,32]]
    ],
    [
      [[1,2,0],
      [3,5,-1]],

      [[10,2,0],
      [1,0,2]],

      [[5,8,0],
      [2,7,0]],

      [[2,1,9],
      [4,-3,32]]
    ],
    [
      [[1,2,0],
      [3,5,-1]],

      [[10,2,0],
      [1,0,2]],

      [[5,8,0],
      [2,7,0]],

      [[2,1,9],
      [4,-3,32]]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [20]:
import numpy as np

In [21]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [23]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [27]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 4, 3, 3), dtype=float32)


In [29]:
fill_tensor = tf.fill([2,3], 9)
print(fill_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [31]:
tensor_ones = tf.ones(
    shape=[2,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(tensor_ones)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [32]:
ones_line_tensor = tf.ones_like(fill_tensor)
print(ones_line_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [33]:
tensor_zeros = tf.zeros(
    shape=[2,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(tensor_zeros)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [34]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [35]:
print(tf.rank(tensor_three_d))

tf.Tensor(3, shape=(), dtype=int32)


In [36]:
print(tf.size(tensor_three_d))

tf.Tensor(24, shape=(), dtype=int32)


In [38]:
random_tensor = tf.random.normal(
    shape=[3,5],
    mean = 0.0,
    stddev=1.0,
    dtype=tf.dtypes.float16,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 1.095   0.55    0.5747  0.3486  0.326 ]
 [ 0.766  -1.178   1.666  -1.05   -2.135 ]
 [-0.9336 -1.304   0.4133 -0.3198 -0.4204]], shape=(3, 5), dtype=float16)


In [39]:
uniform_tensor = tf.random.uniform(
    shape=[2,3],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[0.7280892  0.95522344 0.64577496]
 [0.7429416  0.01275849 0.1685934 ]], shape=(2, 3), dtype=float32)


In [46]:
tf.random.set_seed(1)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.16513085], shape=(1,), dtype=float32)
tf.Tensor([0.51010704], shape=(1,), dtype=float32)


In [49]:
tf.random.set_seed(1)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.16513085], shape=(1,), dtype=float32)
tf.Tensor([0.51010704], shape=(1,), dtype=float32)
